version: '3'

services: 
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        image: salomaocode/app
        container_name: app
        volumes: 
            - .:/var/www
        ports: 
            - "8080:3000" 
        